apiVersion: v1
data:
  mapRoles: |
    - rolearn: ${WorkerNodeInstanceRole}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system