kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: {{ .Values.master.image }}:{{ .Values.master.version }}
        ports:
        - name: redis-server
          containerPort: 6379
