---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create Bastion host to access EKS worker nodes'

Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access into bastion host
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: Bastion host instance type
    Type: String
    Default: t2.small
    AllowedValues: 
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium 
    ConstraintDescription: must be a valid EC2 instance type.

  VPCStackName:
    Description: >-
      The name of CloudFormation stack creating the VPC
    Type: String
  
  AllowSSHFrom:
    Type: String
    Description: Range of addresses allowed to SSH into Bastion
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 0.0.0.0/0

Mappings:
  AMIMap:
    us-west-2: 
      ImageId: 'ami-01bbe152bf19d0289'
    us-east-1: 
      ImageId: 'ami-009d6802948d06e52'
    us-east-2:
      ImageId: 'ami-02e680c4540db351e'
    eu-central-1:
      ImageId: 'ami-034fffcc6a0063961'
    eu-north-1:
      ImageId: 'ami-07ec6279'
    eu-west-1: 
      ImageId: 'ami-09693313102a30b2c'
    ap-northeast-1:
      ImageId: 'ami-0a2de1c3b415889d2'
    ap-northeast-2:
      ImageId: 'ami-018a9a930060d38aa'
    ap-southeast-1:
      ImageId: 'ami-0b84d2c53ad5250c2'
    ap-southeast-2:
      ImageId: 'ami-08589eca6dcc9b39c'


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'VPC Stack Name'
        Parameters:
        - VPCStackName
      - Label:
          default: 'Bastion host configuration'
        Parameters:
        - KeyName
        - InstanceType
        - AllowSSHFrom

Resources:
  PublicBastionSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow bastion to be accessed via SSH from certain IPs
      VpcId: 
        Fn::ImportValue: !Sub '${VPCStackName}-vpc-id'
      SecurityGroupIngress:
      - CidrIp: !Ref AllowSSHFrom
        Description: !Sub "Allow ssh from ${AllowSSHFrom}"
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
      Tags:
      - Key: Name 
        Value: !Sub '${VPCStackName}-bastion-allow-ssh'
      - Key: auto-delete
        Value: "no"

  Bastion:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Fn::FindInMap:
        - AMIMap
        - !Ref AWS::Region
        - ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue: !Sub '${VPCStackName}-bastion-subnet-id'
      SecurityGroupIds:
      - Fn::ImportValue: !Sub '${VPCStackName}-bastion-sg'
      - !Ref PublicBastionSG
      Tags:
      - Key: Name 
        Value: EKS Bastion
      - Key: auto-delete
        Value: "no"

Outputs:
  BastionDNSName:
    Description: >-
      Bastion Host DNS Name
    Value: !GetAtt Bastion.PublicDnsName