kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: {{ .Values.slave.replicaCount }}
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: {{ .Values.slave.image }}:{{ .Values.slave.version }}
        ports:
        - name: redis-server
          containerPort: 6379
